### PR TITLE
Update child-templates.md with info about accessing parents, embedding templates

### PR DESCRIPTION
**Pull request by barbeque**
* Added info on engine=none, which was the cleanest way I found to make child templates work
 * Info on relative paths to get to parent scopes, with an example
 * General cleanup of information so that the PDF section is hopefully more obvious
 * Reorganized sections

Thanks for the awesome toolkit.

### CODE REVIEW

**Comment by pofider** [comment]
Hm, I'm not sure if this change actually correctly describes the purpose of this extension.

You propose that the child template mostly wants to have the `none` engine selected. However this is mostly not what you want, because without the engine the child template can be replaced with the [asset](https://jsreport.net/learn/assets). 

You can see here that the asset takes the role of child template in your example: https://playground.jsreport.net/studio/workspace/HJKV3A6SZ/10

The current doc for child template doesn't reflect this fully, because the *assets* were added quite recently. However I think that the reason for the *child templates* is true modularization, not only replacing of the static content with `none` engine. The true modularization means that the child template has for example attached a [script](https://jsreport.net/learn/scripts) which fetches the remote data, different from the master template. It has also its own helpers. It is basically independent on the master template, it is full standalone template. It only requires some few input parameters which the master templates passes with `@data` argument. 

The big limitation of child templates is that we cannot simply flow the context (`this`) from the master to them. However hopefully we will one day. 

What do you think? The other changes made in this PR are great and I will gladly use them of course.

**Comment by barbeque** [comment]
I think I understand things a little better now. The asset functionality is likely the right thing to use. It did feel a little bit like I was "fighting" the tool too much to make it do what I wanted.

It might need a good example on modular child templates, since from the name 'child' I always think of it participating in the parent scope (i.e. flowing `this`) and not necessarily just being used as a reusable, modular component (i.e. with `@data`).

Should I edit this and remove the static example? It might be better to add that example to the documentation for assets, and link to that documentation from here. I will also clean up the part where I first mention 'none' to explain that assets may be a better choice.

**Comment by pofider** [comment]
Yes please, remove the static example and clean up the part mentioning `none`.

I will try to highlight the modularity afterwards.

**Comment by barbeque** [comment]
Fixed, please let me know if there's more to do. Thanks for the quick replies.

**Comment by pofider** [comment]
Thank you very much, I will try to add the modularity notes as soon I get some time.

**Pull request merged**
